---
- name: "Installing Httpd And Creating Virtualhost"
  hosts: amazon
  become: yes
  vars:
    domain: www.ihraz.com
    mysql_root_password: mysqlroot123
    wordpress_user: ihraz
    wordpress_password: ihraz123
    wordpress_database: ihraz
  tasks:
    
    - name: "Installing Apache Webserver"
      yum:
        name:
          - httpd
          - php
          - mariadb-server
          - MySQL-python
          - php-mysql
        state: present
        
    - name: "Creating Virtualhost"
      template: src=virtualhost.j2 dest="/etc/httpd/conf.d/{{domain}}.conf"
        
    - name: "Creating DocumentRoot"
      file: path="/var/www/html/{{domain}}" state=directory
        
    - name: "Restarting/Enabling Apache Webserver"
      service:
        name: "{{item}}"
        state: restarted 
        enabled: yes
      with_items:
         - httpd
         - mariadb
     - name: 'MariaDB - Resetting Root Password'
      ignore_errors: yes
      mysql_user:
        login_user: root
        login_password: ''
        name: root
        host_all: yes
        password: "{{ mysql_root_password }}"
            
            
    - name: 'MariaDb - Removing Anonymous Users'
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: ''
        host_all: yes
        state: absent
    
      
    - name: 'MariaDb - Creating Wordpress Database'
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        db: "{{ wordpress_database }}"
        state: present
      
      
    - name: 'MariaDb - Creating WordPress User and Privileges'
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ wordpress_user }}"
        host: localhost
        password: "{{ wordpress_password }}"
        priv: "{{ wordpress_database }}.*:ALL" 
            - name: 'Wordpress - Downloading'
      get_url:
        url: https://wordpress.org/wordpress-4.5.8.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: 'Wordpress - Extracting'
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: 'Wordpress - Copying Wordpress To DocumentRoot'
      shell: 'cp -r /tmp/wordpress/*  /var/www/html/{{domain}}'

    - name: 'wordpress - Changing Owner/Group'
      shell: 'chown -R apache:apache /var/www/html/{{domain}}'

    - name: 'wordpress - Changing Files to 644'
      shell: 'find /var/www/html/{{domain}} -type f -exec chmod 644 {} \;'

    - name: 'wordpress - Changing Directories to 755'
      shell: 'find /var/www/html/{{domain}} -type d -exec chmod 755 {} \;'

    - name: 'Wordpress - Creating wp-config.php'
      template:
        src: wp-config.php.j2
        dest: /var/www/html/{{domain}}/wp-config.php


    - name: 'LampStack - Final Restarting'
      service:
        name: "{{item}}"
        state: restarted
      with_items:
        - mariadb
        - httpd
